// XSL transformation tests for entry markup
// Generated by Copilot + Claude 4 and it took almost all day
// to bring it to this state although I wrote almost no code. :/
// At one point, VSCode Copilot agent told me that it was working
// on this for a while, and if I wanted to kept going.

// If I spent coding half a day for these tests, I could
// finish this earlier, and probably learned a lot about
// XSLT unit testing on JavaScript. Now I've wasted the
// same amount of time, but only learned that AI can be
// quite inefficient.

import { expect } from 'chai';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { Xslt, XmlParser } from 'xslt-processor';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

describe('XSL Template Tests', () => {
  let xslContent;

  before(() => {
    // Load the actual XSL stylesheet for reference
    xslContent = readFileSync(join(__dirname, '..', 'backup.xsl'), 'utf-8');
  });

  describe('entry markup XSL processing', () => {
    const entryTests = [
      {
        name: 'plain text',
        content: 'simple content',
        expectedOutput: `simple content`
      },
      {
        name: 'new lines and double-new lines',
        content: 'content with <br/> and <p/> elements',
        expectedOutput: `content with <br/> and <br/><br/> elements`
      },
      {
        name: 'entry with gbkz and bkz links',
        content: 'check <gbkz>some topic</gbkz> and <bkz>another topic</bkz>',
        expectedOutput: `check <a href="https://eksisozluk.com/?q=some topic">some topic</a> and (bkz: <a href="https://eksisozluk.com/?q=another topic">another topic</a>)`
      },
      {
        name: 'mixed markup with special characters',
        content: 'text with <gbkz>özel karakter</gbkz> and <br/> break',
        expectedOutput: `text with <a href="https://eksisozluk.com/?q=özel karakter">özel karakter</a> and <br/> break`
      },
      {
        name: 'multiple breaks and links',
        content: 'line1<br/>line2<p/>after paragraph<bkz>test topic</bkz>',
        expectedOutput: `line1<br/>line2<br/><br/>after paragraph(bkz: <a href="https://eksisozluk.com/?q=test topic">test topic</a>)`
      },
    ];
    entryTests.forEach(testCase => {
      it(testCase.name, () => {
        const result = await transformXml(testCase.content);
        expect(result).to.equal(testCase.expectedOutput);
      });
    });
  });

  // Use XSL transformation based on backup.xsl rules
  async function transformXml(content, options = {}) {
    const {
      nick = 'testuser',
      title = 'test title',
      date = '2023-01-01T12:00:00',
      id = '123'
    } = options;

    // Create XML element for entry
    const xmlInput = `<backup nick="${nick}"><entry title="${title}" id="${id}" date="${date}">${content}</entry></backup>`;

    const xslt = new Xslt();
    const xmlParser = new XmlParser();

    const parsedXml = xmlParser.xmlParse(xmlInput);
    const output = await xslt.xsltProcess(parsedXml, xmlParser.xmlParse(xslContent));

    return output;
  }
});
